# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f81d46ab4b95836a8e03c42e1233501c5e3dc51a8b31ce3e7a1955fd2f4a88875f25d27f5f5831f1fba95b6e92f9e6d95ee783e0a7e9e0ef94c8a89507f9bd4a

test:
  secret_key_base: 6beef9be43f91b12dcb63e3fe8e968d80b5192f3156e50c8dcb297b4e405750393bebf8ba14b47cdc4f167a67f923643600bece361014304af4ac72d132a5403

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
